[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py loaddata core/fixtures/initial_data.json --ignorenonexistent && python create_superuser.py && gunicorn portfolio.wsgi"
