# Generated by Django 6.0.4 on 2026-04-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_uz', models.TextField(default='Salom! Men Islomov Diyorbek.')),
                ('bio_en', models.TextField(default="Hi! I'm Islomov Diyorbek.")),
                ('stat_years', models.PositiveIntegerField(default=5)),
                ('stat_students', models.PositiveIntegerField(default=200)),
                ('stat_projects', models.PositiveIntegerField(default=30)),
            ],
            options={
                'verbose_name': "Men Haqimda Bo'lim",
                'verbose_name_plural': "Men Haqimda Bo'lim",
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField(default='https://github.com/Islomov-Diyor')),
                ('telegram', models.URLField(default='https://t.me/diyorproger2')),
                ('linkedin', models.URLField(default='#')),
                ('email', models.EmailField(default='diyorbekshaxrisabz@gmail.com', max_length=254)),
                ('location', models.CharField(default='Uzbekistan 🇺🇿', max_length=100)),
                ('youtube', models.URLField(default='https://www.youtube.com/@diyorproger')),
            ],
            options={
                'verbose_name': "Aloqa Ma'lumotlari",
                'verbose_name_plural': "Aloqa Ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Kiruvchi Xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ISLOMOV DIYORBEK', max_length=200)),
                ('badge', models.CharField(default='ISHGA TAYYOR', max_length=100)),
                ('desc', models.TextField(default="Full Stack Developer va IT/CS/AT o'qituvchisi.")),
                ('btn1_text', models.CharField(default="Loyihalarni Ko'rish", max_length=100)),
                ('btn2_text', models.CharField(default="Bog'lanish", max_length=100)),
                ('roles', models.TextField(default='Full Stack Developer, IT/CS/AT Teacher, React & Node.js, Python & SQL', help_text='Vergul bilan ajrating')),
            ],
            options={
                'verbose_name': "Hero Bo'lim",
                'verbose_name_plural': "Hero Bo'lim",
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('emoji', models.CharField(default='💡', max_length=10)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Full Stack'), ('talim', "Ta'lim")], default='frontend', max_length=20)),
                ('desc', models.TextField()),
                ('tags', models.CharField(help_text='Vergul bilan ajrating', max_length=300)),
                ('demo_url', models.URLField(default='#')),
                ('github_url', models.URLField(default='#')),
                ('gradient', models.CharField(default='135deg,#001a1f 0%,#003344 50%,#00f5ff0d 100%', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.PositiveSmallIntegerField(default=80, help_text='0 dan 100 gacha')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Ko'nikma",
                'verbose_name_plural': "Ko'nikmalar",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('letter', models.CharField(help_text='Avatar uchun bitta harf', max_length=1)),
                ('course_year', models.CharField(help_text='Masalan: Web kursi, 2021', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "O'quvchi Fikri",
                'verbose_name_plural': "O'quvchilar Fikri",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Ta'lim Tarixi",
                'verbose_name_plural': "Ta'lim Tarixi",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(help_text='https://www.youtube.com/watch?v=XXXXX yoki https://youtu.be/XXXXX')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Video Dars',
                'verbose_name_plural': 'Video Darslar',
                'ordering': ['order'],
            },
        ),
    ]
